version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=n8n
    volumes:
      - n8n_data:/home/node/.n8n

  app:
    image: abubakar352/app:0.0.1.RELEASE
    ports:
      - 8000:8000


volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local